<?php

namespace AppBundle\Repository;

/**
 * GameMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
