<?php

namespace AppBundle\Repository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getActiveSeason()
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder->select('s')
            ->from('AppBundle:Season', 's')
            ->where('s.active = 1');

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
